/**
 * TEMPORARY DUMMY DATA - replace with real listings when available.
 * Do not add these to lib/brand-data.ts.
 */

export interface DummyProduct {
  id: string;
  name: string;
  price: number;
  priceOnRequest?: boolean;
  image: string;
  link: string;
  brandName: string;
}

export const dummyProductsData: Record<string, DummyProduct[]> = {
  cables: [
    {
      id: "dummy-cable-4mm",
      name: "4mm Solar DC Cable (100m Roll)",
      price: 14500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-cable-6mm",
      name: "6mm Solar DC Cable (100m Roll)",
      price: 21000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-cable-10mm",
      name: "10mm Heavy Duty DC Cable",
      price: 34000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-cable-earthing",
      name: "16mm Earthing Copper Cable",
      price: 18500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-cable-ac-4core",
      name: "4-Core AC Armoured Cable 50m",
      price: 29000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
  ],
  breakers: [
    {
      id: "dummy-breaker-dc-63a",
      name: "DC Miniature Circuit Breaker 2P 63A",
      price: 2800,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-breaker-dc-125a",
      name: "DC Moulded Case Circuit Breaker 125A",
      price: 8500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-spd-dc",
      name: "DC Surge Protection Device (SPD) 1000V",
      price: 4500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-ac-isolator",
      name: "AC Rotary Isolator Switch 4P 63A",
      price: 3500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-fuse-pv",
      name: "PV Fuse Link & Holder 15A 1000V",
      price: 1200,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
  ],
  accessories: [
    {
      id: "dummy-mc4-pair",
      name: "MC4 Solar Connector Pairs (Pack of 10)",
      price: 1500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-mounting-l-feet",
      name: "Aluminum L-Feet Roof Mounting Brackets",
      price: 450,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-rail-clamp",
      name: "Mid Clamp & End Clamp Set for Panels",
      price: 250,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-wifi-dongle",
      name: "Inverter WiFi / LAN Monitoring Stick",
      price: 6500,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-cable-ties",
      name: "UV Resistant Cable Ties (Pack of 100)",
      price: 800,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
  ],
  powerBanks: [
    {
      id: "dummy-powerbank-1kwh",
      name: "Portable All-in-One Power Bank 1.2kWh",
      price: 95000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-powerbank-2kwh",
      name: "Solar Generator Power Station 2.0kWh",
      price: 175000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-powerbank-500wh",
      name: "Compact Solar Power Bank 500Wh",
      price: 45000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-powerbank-300wh",
      name: "Mini Emergency Power Station 300Wh",
      price: 28000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-powerbank-outdoor",
      name: "Outdoor Camping Power Hub 1.5kWh",
      price: 125000,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
  ],
  fireExtinguishers: [
    {
      id: "dummy-fire-abc",
      name: "ABC Dry Powder Fire Extinguisher 6kg",
      price: 0,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-fire-co2",
      name: "CO2 Fire Extinguisher 5kg",
      price: 0,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-fire-blanket",
      name: "Fire Blanket 1.2m x 1.2m",
      price: 0,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-fire-bracket",
      name: "Wall Bracket for Fire Extinguisher",
      price: 0,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
    {
      id: "dummy-fire-refill",
      name: "Fire Extinguisher Refill Service",
      price: 0,
      priceOnRequest: true,
      image: "/dummy/placeholder.svg",
      link: "/shop",
      brandName: "Generic",
    },
  ],
};
